INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_00", ROM0
opcode_handler_00:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_01", ROM0
opcode_handler_01:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_02", ROM0
opcode_handler_02:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_03", ROM0
opcode_handler_03:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_04", ROM0
opcode_handler_04:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_05", ROM0
opcode_handler_05:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_06", ROM0
opcode_handler_06:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_07", ROM0
opcode_handler_07:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_08", ROM0
opcode_handler_08:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_09", ROM0
opcode_handler_09:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0A", ROM0
opcode_handler_0A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0B", ROM0
opcode_handler_0B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0C", ROM0
opcode_handler_0C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0D", ROM0
opcode_handler_0D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0E", ROM0
opcode_handler_0E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_0F", ROM0
opcode_handler_0F:: ;N/A
	db RETURN
