INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_10", ROM0
opcode_handler_10:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_11", ROM0
opcode_handler_11:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_12", ROM0
opcode_handler_12:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_13", ROM0
opcode_handler_13:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_14", ROM0
opcode_handler_14:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_15", ROM0
opcode_handler_15:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_16", ROM0
opcode_handler_16:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_17", ROM0
opcode_handler_17:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_18", ROM0
opcode_handler_18:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_19", ROM0
opcode_handler_19:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1A", ROM0
opcode_handler_1A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1B", ROM0
opcode_handler_1B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1C", ROM0
opcode_handler_1C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1D", ROM0
opcode_handler_1D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1E", ROM0
opcode_handler_1E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_1F", ROM0
opcode_handler_1F:: ;N/A
	db RETURN
