INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_20", ROM0
opcode_handler_20:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_21", ROM0
opcode_handler_21:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_22", ROM0
opcode_handler_22:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_23", ROM0
opcode_handler_23:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_24", ROM0
opcode_handler_24:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_25", ROM0
opcode_handler_25:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_26", ROM0
opcode_handler_26:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_27", ROM0
opcode_handler_27:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_28", ROM0
opcode_handler_28:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_29", ROM0
opcode_handler_29:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2A", ROM0
opcode_handler_2A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2B", ROM0
opcode_handler_2B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2C", ROM0
opcode_handler_2C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2D", ROM0
opcode_handler_2D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2E", ROM0
opcode_handler_2E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_2F", ROM0
opcode_handler_2F:: ;N/A
	db RETURN
