INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_30", ROM0
opcode_handler_30:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_31", ROM0
opcode_handler_31:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_32", ROM0
opcode_handler_32:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_33", ROM0
opcode_handler_33:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_34", ROM0
opcode_handler_34:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_35", ROM0
opcode_handler_35:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_36", ROM0
opcode_handler_36:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_37", ROM0
opcode_handler_37:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_38", ROM0
opcode_handler_38:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_39", ROM0
opcode_handler_39:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3A", ROM0
opcode_handler_3A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3B", ROM0
opcode_handler_3B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3C", ROM0
opcode_handler_3C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3D", ROM0
opcode_handler_3D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3E", ROM0
opcode_handler_3E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_3F", ROM0
opcode_handler_3F:: ;N/A
	db RETURN
