INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_40", ROM0
opcode_handler_40:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_41", ROM0
opcode_handler_41:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_42", ROM0
opcode_handler_42:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_43", ROM0
opcode_handler_43:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_44", ROM0
opcode_handler_44:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_45", ROM0
opcode_handler_45:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_46", ROM0
opcode_handler_46:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_47", ROM0
opcode_handler_47:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_48", ROM0
opcode_handler_48:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_49", ROM0
opcode_handler_49:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4A", ROM0
opcode_handler_4A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4B", ROM0
opcode_handler_4B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4C", ROM0
opcode_handler_4C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4D", ROM0
opcode_handler_4D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4E", ROM0
opcode_handler_4E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_4F", ROM0
opcode_handler_4F:: ;N/A
	db RETURN
