INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_50", ROM0
opcode_handler_50:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_51", ROM0
opcode_handler_51:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_52", ROM0
opcode_handler_52:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_53", ROM0
opcode_handler_53:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_54", ROM0
opcode_handler_54:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_55", ROM0
opcode_handler_55:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_56", ROM0
opcode_handler_56:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_57", ROM0
opcode_handler_57:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_58", ROM0
opcode_handler_58:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_59", ROM0
opcode_handler_59:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5A", ROM0
opcode_handler_5A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5B", ROM0
opcode_handler_5B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5C", ROM0
opcode_handler_5C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5D", ROM0
opcode_handler_5D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5E", ROM0
opcode_handler_5E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_5F", ROM0
opcode_handler_5F:: ;N/A
	db RETURN
