INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_70", ROM0
opcode_handler_70:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_71", ROM0
opcode_handler_71:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_72", ROM0
opcode_handler_72:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_73", ROM0
opcode_handler_73:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_74", ROM0
opcode_handler_74:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_75", ROM0
opcode_handler_75:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_76", ROM0
opcode_handler_76:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_77", ROM0
opcode_handler_77:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_78", ROM0
opcode_handler_78:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_79", ROM0
opcode_handler_79:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7A", ROM0
opcode_handler_7A:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7B", ROM0
opcode_handler_7B:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7C", ROM0
opcode_handler_7C:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7D", ROM0
opcode_handler_7D:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7E", ROM0
opcode_handler_7E:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_7F", ROM0
opcode_handler_7F:: ;N/A
	db RETURN
