INCLUDE "emu/macrocodes.inc"
SECTION "OPCODE_HANDLER_F0", ROM0
opcode_handler_F0:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F1", ROM0
opcode_handler_F1:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F2", ROM0
opcode_handler_F2:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F3", ROM0
opcode_handler_F3:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F4", ROM0
opcode_handler_F4:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F5", ROM0
opcode_handler_F5:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F6", ROM0
opcode_handler_F6:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F7", ROM0
opcode_handler_F7:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F8", ROM0
opcode_handler_F8:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_F9", ROM0
opcode_handler_F9:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FA", ROM0
opcode_handler_FA:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FB", ROM0
opcode_handler_FB:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FC", ROM0
opcode_handler_FC:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FD", ROM0
opcode_handler_FD:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FE", ROM0
opcode_handler_FE:: ;N/A
	db RETURN
SECTION "OPCODE_HANDLER_FF", ROM0
opcode_handler_FF:: ;N/A
	db RETURN
